# Book settings
title: Gas Dynamics notes
author: Kyle Niemeyer
logo: logo.jpg

# Bibliography settings
bibtex_bibfiles:
  - references.bib

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    html_show_copyright: false
    #mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    - smartquotes
    #- substitution

repository:
  url: https://github.com/kyleniemeyer/gas-dynamics-notes
  branch: main

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  extra_footer: |
